/* eslint-disable */
import Long from "long";
import { makeGenericClientConstructor, } from "@grpc/grpc-js";
import _m0 from "protobufjs/minimal";
import { ModifyGuildRequest, ModifyGuildResponse, CreateGuildChannelRequest, CreateGuildChannelResponse, ModifyGuildChannelPositionsRequest, ModifyGuildChannelPositionsResponse, AddGuildMemberRequest, AddGuildMemberResponse, ModifyGuildMemberRequest, ModifyGuildMemberResponse, ModifyCurrentUserNickRequest, ModifyCurrentUserNickResponse, AddGuildMemberRoleRequest, AddGuildMemberRoleResponse, RemoveGuildMemberRoleRequest, RemoveGuildMemberRoleResponse, RemoveGuildMemberRequest, RemoveGuildMemberResponse, GetGuildBansRequest, GetGuildBansResponse, GetGuildBanRequest, GetGuildBanResponse, CreateGuildBanRequest, CreateGuildBanResponse, RemoveGuildBanRequest, RemoveGuildBanResponse, CreateGuildRoleRequest, CreateGuildRoleResponse, ModifyGuildRolePositionsRequest, ModifyGuildRolePositionsResponse, ModifyGuildRoleRequest, ModifyGuildRoleResponse, DeleteGuildRoleRequest, DeleteGuildRoleResponse, GetGuildPruneCountRequest, GetGuildPruneCountResponse, BeginGuildPruneRequest, BeginGuildPruneResponse, GetGuildVoiceRegionsRequest, GetGuildVoiceRegionsResponse, GetGuildInvitesRequest, GetGuildInvitesResponse, ModifyChannelRequest, ModifyChannelResponse, DeleteChannelRequest, DeleteChannelResponse, GetChannelMessagesRequest, GetChannelMessagesResponse, GetChannelMessageRequest, GetChannelMessageResponse, CreateMessageRequest, CreateMessageResponse, CrosspostMessageRequest, CrosspostMessageResponse, CreateReactionRequest, CreateReactionResponse, DeleteOwnReactionRequest, DeleteOwnReactionResponse, DeleteUserReactionRequest, DeleteUserReactionResponse, DeleteAllReactionsRequest, DeleteAllReactionsResponse, DeleteAllReactionsForEmojiRequest, DeleteAllReactionsForEmojiResponse, EditMessageRequest, EditMessageResponse, DeleteMessageRequest, DeleteMessageResponse, BulkDeleteMessagesRequest, BulkDeleteMessagesResponse, EditChannelPermissionsRequest, EditChannelPermissionsResponse, GetChannelInvitesRequest, GetChannelInvitesResponse, CreateChannelInviteRequest, CreateChannelInviteResponse, DeleteChannelPermissionRequest, DeleteChannelPermissionResponse, FollowNewsChannelRequest, FollowNewsChannelResponse, TriggerTypingIndicatorRequest, TriggerTypingIndicatorResponse, GetPinnedMessagesRequest, GetPinnedMessagesResponse, AddPinnedChannelMessageRequest, AddPinnedChannelMessageResponse, DeletePinnedChannelMessageRequest, DeletePinnedChannelMessageResponse, ListGuildEmojisRequest, ListGuildEmojisResponse, GetGuildEmojiRequest, GetGuildEmojiResponse, CreateGuildEmojiRequest, CreateGuildEmojiResponse, ModifyGuildEmojiRequest, ModifyGuildEmojiResponse, DeleteGuildEmojiRequest, DeleteGuildEmojiResponse, GetCurrentUserRequest, GetCurrentUserResponse, GetUserRequest, GetUserResponse, ModifyCurrentUserRequest, ModifyCurrentUserResponse, LeaveGuildRequest, LeaveGuildResponse, CreateDmRequest, CreateDmResponse, } from "../../discord/v1/rest";
export const protobufPackage = "pylon.gateway.v1.service";
export const GatewayRestService = {
    modifyGuild: {
        path: "/pylon.gateway.v1.service.GatewayRest/ModifyGuild",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(ModifyGuildRequest.encode(value).finish()),
        requestDeserialize: (value) => ModifyGuildRequest.decode(value),
        responseSerialize: (value) => Buffer.from(ModifyGuildResponse.encode(value).finish()),
        responseDeserialize: (value) => ModifyGuildResponse.decode(value),
    },
    createGuildChannel: {
        path: "/pylon.gateway.v1.service.GatewayRest/CreateGuildChannel",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(CreateGuildChannelRequest.encode(value).finish()),
        requestDeserialize: (value) => CreateGuildChannelRequest.decode(value),
        responseSerialize: (value) => Buffer.from(CreateGuildChannelResponse.encode(value).finish()),
        responseDeserialize: (value) => CreateGuildChannelResponse.decode(value),
    },
    modifyGuildChannelPositions: {
        path: "/pylon.gateway.v1.service.GatewayRest/ModifyGuildChannelPositions",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(ModifyGuildChannelPositionsRequest.encode(value).finish()),
        requestDeserialize: (value) => ModifyGuildChannelPositionsRequest.decode(value),
        responseSerialize: (value) => Buffer.from(ModifyGuildChannelPositionsResponse.encode(value).finish()),
        responseDeserialize: (value) => ModifyGuildChannelPositionsResponse.decode(value),
    },
    addGuildMember: {
        path: "/pylon.gateway.v1.service.GatewayRest/AddGuildMember",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(AddGuildMemberRequest.encode(value).finish()),
        requestDeserialize: (value) => AddGuildMemberRequest.decode(value),
        responseSerialize: (value) => Buffer.from(AddGuildMemberResponse.encode(value).finish()),
        responseDeserialize: (value) => AddGuildMemberResponse.decode(value),
    },
    modifyGuildMember: {
        path: "/pylon.gateway.v1.service.GatewayRest/ModifyGuildMember",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(ModifyGuildMemberRequest.encode(value).finish()),
        requestDeserialize: (value) => ModifyGuildMemberRequest.decode(value),
        responseSerialize: (value) => Buffer.from(ModifyGuildMemberResponse.encode(value).finish()),
        responseDeserialize: (value) => ModifyGuildMemberResponse.decode(value),
    },
    modifyCurrentUserNick: {
        path: "/pylon.gateway.v1.service.GatewayRest/ModifyCurrentUserNick",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(ModifyCurrentUserNickRequest.encode(value).finish()),
        requestDeserialize: (value) => ModifyCurrentUserNickRequest.decode(value),
        responseSerialize: (value) => Buffer.from(ModifyCurrentUserNickResponse.encode(value).finish()),
        responseDeserialize: (value) => ModifyCurrentUserNickResponse.decode(value),
    },
    addGuildMemberRole: {
        path: "/pylon.gateway.v1.service.GatewayRest/AddGuildMemberRole",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(AddGuildMemberRoleRequest.encode(value).finish()),
        requestDeserialize: (value) => AddGuildMemberRoleRequest.decode(value),
        responseSerialize: (value) => Buffer.from(AddGuildMemberRoleResponse.encode(value).finish()),
        responseDeserialize: (value) => AddGuildMemberRoleResponse.decode(value),
    },
    removeGuildMemberRole: {
        path: "/pylon.gateway.v1.service.GatewayRest/RemoveGuildMemberRole",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(RemoveGuildMemberRoleRequest.encode(value).finish()),
        requestDeserialize: (value) => RemoveGuildMemberRoleRequest.decode(value),
        responseSerialize: (value) => Buffer.from(RemoveGuildMemberRoleResponse.encode(value).finish()),
        responseDeserialize: (value) => RemoveGuildMemberRoleResponse.decode(value),
    },
    removeGuildMember: {
        path: "/pylon.gateway.v1.service.GatewayRest/RemoveGuildMember",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(RemoveGuildMemberRequest.encode(value).finish()),
        requestDeserialize: (value) => RemoveGuildMemberRequest.decode(value),
        responseSerialize: (value) => Buffer.from(RemoveGuildMemberResponse.encode(value).finish()),
        responseDeserialize: (value) => RemoveGuildMemberResponse.decode(value),
    },
    getGuildBans: {
        path: "/pylon.gateway.v1.service.GatewayRest/GetGuildBans",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(GetGuildBansRequest.encode(value).finish()),
        requestDeserialize: (value) => GetGuildBansRequest.decode(value),
        responseSerialize: (value) => Buffer.from(GetGuildBansResponse.encode(value).finish()),
        responseDeserialize: (value) => GetGuildBansResponse.decode(value),
    },
    getGuildBan: {
        path: "/pylon.gateway.v1.service.GatewayRest/GetGuildBan",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(GetGuildBanRequest.encode(value).finish()),
        requestDeserialize: (value) => GetGuildBanRequest.decode(value),
        responseSerialize: (value) => Buffer.from(GetGuildBanResponse.encode(value).finish()),
        responseDeserialize: (value) => GetGuildBanResponse.decode(value),
    },
    createGuildBan: {
        path: "/pylon.gateway.v1.service.GatewayRest/CreateGuildBan",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(CreateGuildBanRequest.encode(value).finish()),
        requestDeserialize: (value) => CreateGuildBanRequest.decode(value),
        responseSerialize: (value) => Buffer.from(CreateGuildBanResponse.encode(value).finish()),
        responseDeserialize: (value) => CreateGuildBanResponse.decode(value),
    },
    removeGuildBan: {
        path: "/pylon.gateway.v1.service.GatewayRest/RemoveGuildBan",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(RemoveGuildBanRequest.encode(value).finish()),
        requestDeserialize: (value) => RemoveGuildBanRequest.decode(value),
        responseSerialize: (value) => Buffer.from(RemoveGuildBanResponse.encode(value).finish()),
        responseDeserialize: (value) => RemoveGuildBanResponse.decode(value),
    },
    createGuildRole: {
        path: "/pylon.gateway.v1.service.GatewayRest/CreateGuildRole",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(CreateGuildRoleRequest.encode(value).finish()),
        requestDeserialize: (value) => CreateGuildRoleRequest.decode(value),
        responseSerialize: (value) => Buffer.from(CreateGuildRoleResponse.encode(value).finish()),
        responseDeserialize: (value) => CreateGuildRoleResponse.decode(value),
    },
    modifyGuildRolePositions: {
        path: "/pylon.gateway.v1.service.GatewayRest/ModifyGuildRolePositions",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(ModifyGuildRolePositionsRequest.encode(value).finish()),
        requestDeserialize: (value) => ModifyGuildRolePositionsRequest.decode(value),
        responseSerialize: (value) => Buffer.from(ModifyGuildRolePositionsResponse.encode(value).finish()),
        responseDeserialize: (value) => ModifyGuildRolePositionsResponse.decode(value),
    },
    modifyGuildRole: {
        path: "/pylon.gateway.v1.service.GatewayRest/ModifyGuildRole",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(ModifyGuildRoleRequest.encode(value).finish()),
        requestDeserialize: (value) => ModifyGuildRoleRequest.decode(value),
        responseSerialize: (value) => Buffer.from(ModifyGuildRoleResponse.encode(value).finish()),
        responseDeserialize: (value) => ModifyGuildRoleResponse.decode(value),
    },
    deleteGuildRole: {
        path: "/pylon.gateway.v1.service.GatewayRest/DeleteGuildRole",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(DeleteGuildRoleRequest.encode(value).finish()),
        requestDeserialize: (value) => DeleteGuildRoleRequest.decode(value),
        responseSerialize: (value) => Buffer.from(DeleteGuildRoleResponse.encode(value).finish()),
        responseDeserialize: (value) => DeleteGuildRoleResponse.decode(value),
    },
    getGuildPruneCount: {
        path: "/pylon.gateway.v1.service.GatewayRest/GetGuildPruneCount",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(GetGuildPruneCountRequest.encode(value).finish()),
        requestDeserialize: (value) => GetGuildPruneCountRequest.decode(value),
        responseSerialize: (value) => Buffer.from(GetGuildPruneCountResponse.encode(value).finish()),
        responseDeserialize: (value) => GetGuildPruneCountResponse.decode(value),
    },
    beginGuildPrune: {
        path: "/pylon.gateway.v1.service.GatewayRest/BeginGuildPrune",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(BeginGuildPruneRequest.encode(value).finish()),
        requestDeserialize: (value) => BeginGuildPruneRequest.decode(value),
        responseSerialize: (value) => Buffer.from(BeginGuildPruneResponse.encode(value).finish()),
        responseDeserialize: (value) => BeginGuildPruneResponse.decode(value),
    },
    getGuildVoiceRegions: {
        path: "/pylon.gateway.v1.service.GatewayRest/GetGuildVoiceRegions",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(GetGuildVoiceRegionsRequest.encode(value).finish()),
        requestDeserialize: (value) => GetGuildVoiceRegionsRequest.decode(value),
        responseSerialize: (value) => Buffer.from(GetGuildVoiceRegionsResponse.encode(value).finish()),
        responseDeserialize: (value) => GetGuildVoiceRegionsResponse.decode(value),
    },
    getGuildInvites: {
        path: "/pylon.gateway.v1.service.GatewayRest/GetGuildInvites",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(GetGuildInvitesRequest.encode(value).finish()),
        requestDeserialize: (value) => GetGuildInvitesRequest.decode(value),
        responseSerialize: (value) => Buffer.from(GetGuildInvitesResponse.encode(value).finish()),
        responseDeserialize: (value) => GetGuildInvitesResponse.decode(value),
    },
    modifyChannel: {
        path: "/pylon.gateway.v1.service.GatewayRest/ModifyChannel",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(ModifyChannelRequest.encode(value).finish()),
        requestDeserialize: (value) => ModifyChannelRequest.decode(value),
        responseSerialize: (value) => Buffer.from(ModifyChannelResponse.encode(value).finish()),
        responseDeserialize: (value) => ModifyChannelResponse.decode(value),
    },
    deleteChannel: {
        path: "/pylon.gateway.v1.service.GatewayRest/DeleteChannel",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(DeleteChannelRequest.encode(value).finish()),
        requestDeserialize: (value) => DeleteChannelRequest.decode(value),
        responseSerialize: (value) => Buffer.from(DeleteChannelResponse.encode(value).finish()),
        responseDeserialize: (value) => DeleteChannelResponse.decode(value),
    },
    getChannelMessages: {
        path: "/pylon.gateway.v1.service.GatewayRest/GetChannelMessages",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(GetChannelMessagesRequest.encode(value).finish()),
        requestDeserialize: (value) => GetChannelMessagesRequest.decode(value),
        responseSerialize: (value) => Buffer.from(GetChannelMessagesResponse.encode(value).finish()),
        responseDeserialize: (value) => GetChannelMessagesResponse.decode(value),
    },
    getChannelMessage: {
        path: "/pylon.gateway.v1.service.GatewayRest/GetChannelMessage",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(GetChannelMessageRequest.encode(value).finish()),
        requestDeserialize: (value) => GetChannelMessageRequest.decode(value),
        responseSerialize: (value) => Buffer.from(GetChannelMessageResponse.encode(value).finish()),
        responseDeserialize: (value) => GetChannelMessageResponse.decode(value),
    },
    createMessage: {
        path: "/pylon.gateway.v1.service.GatewayRest/CreateMessage",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(CreateMessageRequest.encode(value).finish()),
        requestDeserialize: (value) => CreateMessageRequest.decode(value),
        responseSerialize: (value) => Buffer.from(CreateMessageResponse.encode(value).finish()),
        responseDeserialize: (value) => CreateMessageResponse.decode(value),
    },
    crosspostMessage: {
        path: "/pylon.gateway.v1.service.GatewayRest/CrosspostMessage",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(CrosspostMessageRequest.encode(value).finish()),
        requestDeserialize: (value) => CrosspostMessageRequest.decode(value),
        responseSerialize: (value) => Buffer.from(CrosspostMessageResponse.encode(value).finish()),
        responseDeserialize: (value) => CrosspostMessageResponse.decode(value),
    },
    createReaction: {
        path: "/pylon.gateway.v1.service.GatewayRest/CreateReaction",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(CreateReactionRequest.encode(value).finish()),
        requestDeserialize: (value) => CreateReactionRequest.decode(value),
        responseSerialize: (value) => Buffer.from(CreateReactionResponse.encode(value).finish()),
        responseDeserialize: (value) => CreateReactionResponse.decode(value),
    },
    deleteOwnReaction: {
        path: "/pylon.gateway.v1.service.GatewayRest/DeleteOwnReaction",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(DeleteOwnReactionRequest.encode(value).finish()),
        requestDeserialize: (value) => DeleteOwnReactionRequest.decode(value),
        responseSerialize: (value) => Buffer.from(DeleteOwnReactionResponse.encode(value).finish()),
        responseDeserialize: (value) => DeleteOwnReactionResponse.decode(value),
    },
    deleteUserReaction: {
        path: "/pylon.gateway.v1.service.GatewayRest/DeleteUserReaction",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(DeleteUserReactionRequest.encode(value).finish()),
        requestDeserialize: (value) => DeleteUserReactionRequest.decode(value),
        responseSerialize: (value) => Buffer.from(DeleteUserReactionResponse.encode(value).finish()),
        responseDeserialize: (value) => DeleteUserReactionResponse.decode(value),
    },
    deleteAllReactions: {
        path: "/pylon.gateway.v1.service.GatewayRest/DeleteAllReactions",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(DeleteAllReactionsRequest.encode(value).finish()),
        requestDeserialize: (value) => DeleteAllReactionsRequest.decode(value),
        responseSerialize: (value) => Buffer.from(DeleteAllReactionsResponse.encode(value).finish()),
        responseDeserialize: (value) => DeleteAllReactionsResponse.decode(value),
    },
    deleteAllReactionsForEmoji: {
        path: "/pylon.gateway.v1.service.GatewayRest/DeleteAllReactionsForEmoji",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(DeleteAllReactionsForEmojiRequest.encode(value).finish()),
        requestDeserialize: (value) => DeleteAllReactionsForEmojiRequest.decode(value),
        responseSerialize: (value) => Buffer.from(DeleteAllReactionsForEmojiResponse.encode(value).finish()),
        responseDeserialize: (value) => DeleteAllReactionsForEmojiResponse.decode(value),
    },
    editMessage: {
        path: "/pylon.gateway.v1.service.GatewayRest/EditMessage",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(EditMessageRequest.encode(value).finish()),
        requestDeserialize: (value) => EditMessageRequest.decode(value),
        responseSerialize: (value) => Buffer.from(EditMessageResponse.encode(value).finish()),
        responseDeserialize: (value) => EditMessageResponse.decode(value),
    },
    deleteMessage: {
        path: "/pylon.gateway.v1.service.GatewayRest/DeleteMessage",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(DeleteMessageRequest.encode(value).finish()),
        requestDeserialize: (value) => DeleteMessageRequest.decode(value),
        responseSerialize: (value) => Buffer.from(DeleteMessageResponse.encode(value).finish()),
        responseDeserialize: (value) => DeleteMessageResponse.decode(value),
    },
    bulkDeleteMessages: {
        path: "/pylon.gateway.v1.service.GatewayRest/BulkDeleteMessages",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(BulkDeleteMessagesRequest.encode(value).finish()),
        requestDeserialize: (value) => BulkDeleteMessagesRequest.decode(value),
        responseSerialize: (value) => Buffer.from(BulkDeleteMessagesResponse.encode(value).finish()),
        responseDeserialize: (value) => BulkDeleteMessagesResponse.decode(value),
    },
    editChannelPermissions: {
        path: "/pylon.gateway.v1.service.GatewayRest/EditChannelPermissions",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(EditChannelPermissionsRequest.encode(value).finish()),
        requestDeserialize: (value) => EditChannelPermissionsRequest.decode(value),
        responseSerialize: (value) => Buffer.from(EditChannelPermissionsResponse.encode(value).finish()),
        responseDeserialize: (value) => EditChannelPermissionsResponse.decode(value),
    },
    getChannelInvites: {
        path: "/pylon.gateway.v1.service.GatewayRest/GetChannelInvites",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(GetChannelInvitesRequest.encode(value).finish()),
        requestDeserialize: (value) => GetChannelInvitesRequest.decode(value),
        responseSerialize: (value) => Buffer.from(GetChannelInvitesResponse.encode(value).finish()),
        responseDeserialize: (value) => GetChannelInvitesResponse.decode(value),
    },
    createChannelInvite: {
        path: "/pylon.gateway.v1.service.GatewayRest/CreateChannelInvite",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(CreateChannelInviteRequest.encode(value).finish()),
        requestDeserialize: (value) => CreateChannelInviteRequest.decode(value),
        responseSerialize: (value) => Buffer.from(CreateChannelInviteResponse.encode(value).finish()),
        responseDeserialize: (value) => CreateChannelInviteResponse.decode(value),
    },
    deleteChannelPermission: {
        path: "/pylon.gateway.v1.service.GatewayRest/DeleteChannelPermission",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(DeleteChannelPermissionRequest.encode(value).finish()),
        requestDeserialize: (value) => DeleteChannelPermissionRequest.decode(value),
        responseSerialize: (value) => Buffer.from(DeleteChannelPermissionResponse.encode(value).finish()),
        responseDeserialize: (value) => DeleteChannelPermissionResponse.decode(value),
    },
    followNewsChannel: {
        path: "/pylon.gateway.v1.service.GatewayRest/FollowNewsChannel",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(FollowNewsChannelRequest.encode(value).finish()),
        requestDeserialize: (value) => FollowNewsChannelRequest.decode(value),
        responseSerialize: (value) => Buffer.from(FollowNewsChannelResponse.encode(value).finish()),
        responseDeserialize: (value) => FollowNewsChannelResponse.decode(value),
    },
    triggerTypingIndicator: {
        path: "/pylon.gateway.v1.service.GatewayRest/TriggerTypingIndicator",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(TriggerTypingIndicatorRequest.encode(value).finish()),
        requestDeserialize: (value) => TriggerTypingIndicatorRequest.decode(value),
        responseSerialize: (value) => Buffer.from(TriggerTypingIndicatorResponse.encode(value).finish()),
        responseDeserialize: (value) => TriggerTypingIndicatorResponse.decode(value),
    },
    getPinnedMessages: {
        path: "/pylon.gateway.v1.service.GatewayRest/GetPinnedMessages",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(GetPinnedMessagesRequest.encode(value).finish()),
        requestDeserialize: (value) => GetPinnedMessagesRequest.decode(value),
        responseSerialize: (value) => Buffer.from(GetPinnedMessagesResponse.encode(value).finish()),
        responseDeserialize: (value) => GetPinnedMessagesResponse.decode(value),
    },
    addPinnedChannelMessage: {
        path: "/pylon.gateway.v1.service.GatewayRest/AddPinnedChannelMessage",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(AddPinnedChannelMessageRequest.encode(value).finish()),
        requestDeserialize: (value) => AddPinnedChannelMessageRequest.decode(value),
        responseSerialize: (value) => Buffer.from(AddPinnedChannelMessageResponse.encode(value).finish()),
        responseDeserialize: (value) => AddPinnedChannelMessageResponse.decode(value),
    },
    deletePinnedChannelMessage: {
        path: "/pylon.gateway.v1.service.GatewayRest/DeletePinnedChannelMessage",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(DeletePinnedChannelMessageRequest.encode(value).finish()),
        requestDeserialize: (value) => DeletePinnedChannelMessageRequest.decode(value),
        responseSerialize: (value) => Buffer.from(DeletePinnedChannelMessageResponse.encode(value).finish()),
        responseDeserialize: (value) => DeletePinnedChannelMessageResponse.decode(value),
    },
    listGuildEmojis: {
        path: "/pylon.gateway.v1.service.GatewayRest/ListGuildEmojis",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(ListGuildEmojisRequest.encode(value).finish()),
        requestDeserialize: (value) => ListGuildEmojisRequest.decode(value),
        responseSerialize: (value) => Buffer.from(ListGuildEmojisResponse.encode(value).finish()),
        responseDeserialize: (value) => ListGuildEmojisResponse.decode(value),
    },
    getGuildEmoji: {
        path: "/pylon.gateway.v1.service.GatewayRest/GetGuildEmoji",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(GetGuildEmojiRequest.encode(value).finish()),
        requestDeserialize: (value) => GetGuildEmojiRequest.decode(value),
        responseSerialize: (value) => Buffer.from(GetGuildEmojiResponse.encode(value).finish()),
        responseDeserialize: (value) => GetGuildEmojiResponse.decode(value),
    },
    createGuildEmoji: {
        path: "/pylon.gateway.v1.service.GatewayRest/CreateGuildEmoji",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(CreateGuildEmojiRequest.encode(value).finish()),
        requestDeserialize: (value) => CreateGuildEmojiRequest.decode(value),
        responseSerialize: (value) => Buffer.from(CreateGuildEmojiResponse.encode(value).finish()),
        responseDeserialize: (value) => CreateGuildEmojiResponse.decode(value),
    },
    modifyGuildEmoji: {
        path: "/pylon.gateway.v1.service.GatewayRest/ModifyGuildEmoji",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(ModifyGuildEmojiRequest.encode(value).finish()),
        requestDeserialize: (value) => ModifyGuildEmojiRequest.decode(value),
        responseSerialize: (value) => Buffer.from(ModifyGuildEmojiResponse.encode(value).finish()),
        responseDeserialize: (value) => ModifyGuildEmojiResponse.decode(value),
    },
    deleteGuildEmoji: {
        path: "/pylon.gateway.v1.service.GatewayRest/DeleteGuildEmoji",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(DeleteGuildEmojiRequest.encode(value).finish()),
        requestDeserialize: (value) => DeleteGuildEmojiRequest.decode(value),
        responseSerialize: (value) => Buffer.from(DeleteGuildEmojiResponse.encode(value).finish()),
        responseDeserialize: (value) => DeleteGuildEmojiResponse.decode(value),
    },
    getCurrentUser: {
        path: "/pylon.gateway.v1.service.GatewayRest/GetCurrentUser",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(GetCurrentUserRequest.encode(value).finish()),
        requestDeserialize: (value) => GetCurrentUserRequest.decode(value),
        responseSerialize: (value) => Buffer.from(GetCurrentUserResponse.encode(value).finish()),
        responseDeserialize: (value) => GetCurrentUserResponse.decode(value),
    },
    getUser: {
        path: "/pylon.gateway.v1.service.GatewayRest/GetUser",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(GetUserRequest.encode(value).finish()),
        requestDeserialize: (value) => GetUserRequest.decode(value),
        responseSerialize: (value) => Buffer.from(GetUserResponse.encode(value).finish()),
        responseDeserialize: (value) => GetUserResponse.decode(value),
    },
    modifyCurrentUser: {
        path: "/pylon.gateway.v1.service.GatewayRest/ModifyCurrentUser",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(ModifyCurrentUserRequest.encode(value).finish()),
        requestDeserialize: (value) => ModifyCurrentUserRequest.decode(value),
        responseSerialize: (value) => Buffer.from(ModifyCurrentUserResponse.encode(value).finish()),
        responseDeserialize: (value) => ModifyCurrentUserResponse.decode(value),
    },
    leaveGuild: {
        path: "/pylon.gateway.v1.service.GatewayRest/LeaveGuild",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(LeaveGuildRequest.encode(value).finish()),
        requestDeserialize: (value) => LeaveGuildRequest.decode(value),
        responseSerialize: (value) => Buffer.from(LeaveGuildResponse.encode(value).finish()),
        responseDeserialize: (value) => LeaveGuildResponse.decode(value),
    },
    createDm: {
        path: "/pylon.gateway.v1.service.GatewayRest/CreateDm",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(CreateDmRequest.encode(value).finish()),
        requestDeserialize: (value) => CreateDmRequest.decode(value),
        responseSerialize: (value) => Buffer.from(CreateDmResponse.encode(value).finish()),
        responseDeserialize: (value) => CreateDmResponse.decode(value),
    },
};
export const GatewayRestClient = makeGenericClientConstructor(GatewayRestService, "pylon.gateway.v1.service.GatewayRest");
if (_m0.util.Long !== Long) {
    _m0.util.Long = Long;
    _m0.configure();
}
